### ISSUE TITLE
Handle xml header

### ISSUE THREAD

**Issue by MTRNord** [PoiScript/strong-xml#11]
Hi how can I handle this header?

`<?xml version="1.0" encoding="UTF-8"?>` If I dont comment it out it crashes with a runtime error when parsing.

**Comment by PoiScript** [comment]
Sorry for the delay. I just updated a commit 3b27b9b4d61cdfc4664aaa994c67cefb16de9137 which adds a test suite for this. xml header will be now ignored when parsing. If you want to prepend the xml header, just use `write!(&writer, "<?xml version="1.0" encoding="UTF-8"?>")?;`.
