### ISSUE TITLE
please include LICENSE file in published crates

### ISSUE THREAD

**Issue by decathorpe** [PoiScript/strong-xml#24]
The MIT license requires that redistributed sources contain the license text. The git repository for strong-xml contains a LICENSE file, but since this file is only in the Cargo workspace root and not in the actual "crate subdirectories", they will not be included when publishing sources to crates.io with "cargo publish".

The simplest solution for this is usually to create symbolic links in the subdirectories (i.e. `LICENSE → ../LICENSE`), assuming you're running "cargo publish" on unix-like systems (mac OS or Linux). On windows, there's no equivalent to functional symlinks, so there the only solution would be to copy the LICENSE file into the subdirectories for all published crates.

**Comment by PoiScript** [comment]
Thanks you for report this, I just published v0.6.3 which includes MIT license file.

**Comment by decathorpe** [comment]
Thanks! :)
