### ISSUE TITLE
Allow serialization to omit when `bool` attribute is `false`

### ISSUE THREAD

**Issue by spikespaz** [PoiScript/strong-xml#33]
I would like the following structure to result in the XML shown after it:
```rust
#[derive(PartialEq, XmlRead, XmlWrite)]
#[xml(tag = "myitem")]
struct MyItem {
	#[xml(attr = "mybool")]
	mybool: bool,
}
```
```xml
<myitem></myitem>
```
What it actually serializes to:
```xml
<myitem mybool="false"></myitem>
```
What it should serialize to if `mybool` is `true`:
```xml
<myitem mybool="true"></myitem>
```

Here is my code at a commit that allows my tests to pass, it is the addition of the unnecessary attributes that are `false` into the strings I test against:
https://github.com/spikespaz/nordvpn-viking/commit/2c988a56bf208064eb1609a621481417f2726761?diff=unified

**Comment by PoiScript** [comment]
You should use `Option<bool>::None` for omitted attribute.

```rust
use strong_xml::{XmlRead, XmlResult, XmlWrite};

#[derive(XmlRead, XmlWrite, PartialEq, Debug)]
#[xml(tag = "foo")]
struct Foo {
    #[xml(attr = "bar")]
    bar: Option<bool>,
}

#[test]
fn test() -> XmlResult<()> {
    assert_eq!((Foo { bar: None }.to_string()?), "<foo/>");

    assert_eq!(
        (Foo { bar: Some(false) }.to_string()?),
        r#"<foo bar="false"/>"#
    );

    Ok(())
}
```
