### ISSUE TITLE
Support tuple structs

### ISSUE THREAD

**Issue by niluxv** [PoiScript/strong-xml#4]
When deriving `XmlRead` for a tuple struct, I get the following error:
```
error: proc-macro derive panicked
  --> src/main.rs:23:45
   |
23 | #[derive(Debug, Clone, PartialEq, XmlWrite, XmlRead)]
   |                                             ^^^^^^^
   |
   = help: message: called `Option::unwrap()` on a `None` value
```
MWE:
```rust
#[derive(Debug, Clone, PartialEq, XmlWrite, XmlRead)]
#[xml(tag = "tuple-struct")]
pub struct TupleStruct (
    #[xml(text)] String,
);
```
I think it is the unwrap on [line 225 of `types.rs`](https://github.com/PoiScript/strong-xml/blob/b726b304a9ccffea0aef169bae04674397b967ad/strong-xml-derive/src/types.rs#L225), since `field.ident` (field name) is not defined (there is no field name).

It would be nice if tuple structs are supported, or at least document in the README that tuple structs aren't supported by the derive.

**Comment by PoiScript** [comment]
I have published the v0.4 which implements the support of newtype_struct like `struct Foo(T)` where `T: XmlRead + XmlWrite`. 

For other types of tuples structs, I'll still considering how to make it work properly.

**Comment by luqmana** [comment]
I also ran into this while trying to parse something like this
I'd like to parse something like this:
```xml
<Response><Status value="200"/></Response>
```
using:
```rust
#[derive(XmlRead, XmlWrite)]
#[xml(tag = "Status")]
struct Status(#[xml(attr = "value")] usize);

#[derive(XmlRead, XmlWrite)]
#[xml(tag = "Response")]
struct Response {
    #[xml(child = "Status")]
    status: Status,
}
```

**Comment by PoiScript** [comment]
If you're not using newtype struct, please try out v0.6.0-alpha which includes the support for general tuple struct and tuple enum.

I'll publish a formal v0.6 version once it's able to handle both newtype struct and tuple struct.

**Comment by niluxv** [comment]
My example does work under v0.6.0-alpha.
Thank you!
